#!/usr/bin/env python3
"""One-shot: self-host Aurora fonts (Inter, Fraunces, JetBrains Mono).

Pulls woff2 from Google's css2 API with a modern Chrome UA, keeps only the
latin + latin-ext subsets, downloads each file into static/fonts/, and writes
static/fonts/fonts.css with local @font-face rules. No runtime CDN.
"""
import re, sys, subprocess, pathlib

UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36")

# family spec -> (css2 query, filename slug)
FAMILIES = [
    ("Inter:wght@300;400;500;600;700", "inter"),
    # Fraunces as two variable files (roman + italic), full optical-size + weight range
    ("Fraunces:ital,opsz,wght@0,9..144,300..600;1,9..144,300..600", "fraunces"),
    ("JetBrains+Mono:wght@400;500", "jetbrains-mono"),
]

OUT = pathlib.Path("static/fonts")
OUT.mkdir(parents=True, exist_ok=True)

def fetch(url):
    # urllib can't verify SSL in this env; curl can. Shell out.
    out = subprocess.run(
        ["curl", "-sS", "-L", "-m", "40", "-A", UA, url],
        capture_output=True, check=True,
    )
    return out.stdout

FACE_RE = re.compile(r"/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{[^}]*\})", re.S)
PROP = lambda block, name: (re.search(rf"{name}:\s*([^;]+);", block) or [None, ""])[1].strip()

css_out = ["/* Aurora self-hosted fonts. Generated by fetch_fonts.py. Do not hand-edit. */"]
seen = set()
count = 0

for query, slug in FAMILIES:
    css = fetch(f"https://fonts.googleapis.com/css2?family={query}&display=swap").decode("utf-8")
    for subset, block in FACE_RE.findall(css):
        if subset not in ("latin", "latin-ext"):
            continue
        fam = PROP(block, "font-family").strip("'\"")
        style = PROP(block, "font-style") or "normal"
        weight = PROP(block, "font-weight") or "400"
        urlm = re.search(r"url\(([^)]+)\)\s*format\(['\"]woff2['\"]\)", block)
        if not urlm:
            urlm = re.search(r"url\(([^)]+)\)", block)
        if not urlm:
            continue
        src_url = urlm.group(1).strip("'\"")
        wlabel = weight.replace(" ", "_")
        ext = "-ext" if subset == "latin-ext" else ""
        sty = "italic" if "italic" in style else "normal"
        fname = f"{slug}-{sty}-{wlabel}{ext}.woff2"
        key = fname
        if key in seen:
            continue
        seen.add(key)
        data = fetch(src_url)
        (OUT / fname).write_bytes(data)
        count += 1
        unicode_range = PROP(block, "unicode-range")
        css_out.append(
            "@font-face {\n"
            f"  font-family: '{fam}';\n"
            f"  font-style: {style};\n"
            f"  font-weight: {weight};\n"
            "  font-display: swap;\n"
            f"  src: url('/static/fonts/{fname}') format('woff2');\n"
            + (f"  unicode-range: {unicode_range};\n" if unicode_range else "")
            + "}"
        )
        print(f"  + {fname}  ({len(data)//1024} KB)  [{fam} {style} {weight} {subset}]")

_css_text = "\n".join(css_out) + "\n"
(OUT / "fonts.css").write_text(_css_text, encoding="utf-8")
print(f"\nDownloaded {count} font files -> static/fonts/")
print(f"Wrote static/fonts/fonts.css ({len(_css_text)} bytes)")
